services:
  factory-php:
    build:
      target: dev-build
    volumes:
      - './app:/var/www/html:rw'
      - './DockerPHP/sampleData/products.csv:/var/www/html/importData/sampleProducts.csv:r'
  
  factory-nginx:
    volumes:
      - './app:/var/www/html:r'
