services:
  factory-php:
    volumes:
      - './app:/var/www/html:rw'
      - './DockerPHP/init-php-dev.sh:/var/www/init-php.sh:r'
      - './DockerPHP/sampleData/products.csv:/var/www/html/importData/sampleProducts.csv:r'
  
  factory-nginx:
    volumes:
      - './app:/var/www/html:r'
