framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: {}
        buses:
            messenger.bus.default:
                middleware:
                    - App\Common\Messenger\AmqpMiddleware
                    - App\Common\Messenger\AuditMiddleware
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            manufacturing:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: true
                    exchange:
                        name: product_logs
                        type: topic
                    queues:
                        products_catalogue:
                            # name: 'products_catalogue'
                            binding_keys: ['product.shipped']
                        products_manufacture:
                            # name: 'products_manufacture'
                            binding_keys: ['product.ordered', 'product.manufactured']
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                # options:
                    # use_notify: true
                    # check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Catalogue\Domain\Model\Messages\ProductOrdered: manufacturing

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
